### ISSUE TITLE
pkg_resources.DistributionNotFound: requests

### ISSUE THREAD

**Issue by gavmckee80** [arista-eosplus/packer-ztpserver#36]
I've just built the VM on macos, for VMWare fusion 

python2.7 ./create-ztpserver.py -H vmware -o ubuntu --vmname ztpserver

The VM builds sucessfully , however when I try to start the ztp server I get the following traceback.

ztpsadmin@ztps:~$ ztps
Traceback (most recent call last):
  File "/usr/local/bin/ztps", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests

Any ideas how to help here ?

**Comment by gavmckee80** [comment]
Adding packer debug log file
[packer-debug.log](https://github.com/arista-eosplus/packer-ztpserver/files/3443319/packer-debug.log)

**Comment by cheynearista** [comment]
@gavmckee80 Do you have package `request` installed?
`pip show requests`

**Comment by gavmckee80** [comment]
@cheynearista 
ztpsadmin@ztps:~$ pip freeze
Warning: cannot find svn location for distribute==0.6.24dev-r0
GnuPGInterface==0.3.2
apt-xapian-index==0.44
argparse==1.2.1
chardet==2.0.1
command-not-found==0.2.44
FIXME: could not find svn URL in dependency_links for this package:
distribute==0.6.24dev-r0
language-selector==0.1
python-apt==0.8.3ubuntu7.3
python-debian==0.1.21ubuntu1
ufw==0.31.1-1
wsgiref==0.1.2
ztpserver==1.3.2

**Comment by gavmckee80** [comment]
@cheynearista 
![image](https://user-images.githubusercontent.com/17826993/62071779-1db34280-b1f2-11e9-8694-85e02472bbfc.png)
I've also tested building a Fedora based image - looks like this goes sour during the install phase

**Comment by gavmckee80** [comment]
@cheynearista 

I think this is an install issue with the requests lib
ztpsadmin@ztps:/usr/share/ztpserver/files/lib$ ls
requests-2.3.0.tar.gz

I see the tar file is there , I do a manual install by unzipping into /tmp and then sudo pip install .

That successfully installs - but it shifts now to a different missing lib (PyYaml)

ztpsadmin@ztps:/$ ztps
Traceback (most recent call last):
  File "/usr/local/bin/ztps", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyyaml 


So I think this is something fundamental going wrong in the build process

**Comment by gavmckee80** [comment]
To fix this I had to do the following 
sudo pip install --index-url=https://pypi.python.org/simple/ pyyaml
sudo pip install --index-url=https://pypi.python.org/simple/ routes
sudo pip install --index-url=https://pypi.python.org/simple/ webob

Maybe we could get these steps integrated to the build,  I think this could just be a problem with the fact that I have to specify the --index-url= option as https .  As these packages are mentioned in the requirements.txt file and not specifying the option leads to an error
